blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: http://happy-coding-clans.github.io/issue-template-generater/
    about: The issue which is not created via http://happy-coding-clans.github.io/issue-template-generater/ will be closed immediately.
